version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - reactor

  reactor:
    build: .
    container_name: reactor
    depends_on:
      - mongo
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/accounts
    networks:
      - reactor

networks:
  reactor:
    driver: bridge
